version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: tp-mongodb
    environment:
      MONGO_INITDB_DATABASE: tp_programacion
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: